const legendCats = [
  // Legend Cats from Main Chapters
  {
    name: "Valkyrie Cat",
    evolved: "True Valkyrie Cat",
    true: "Holy Valkyrie Cat",
    type: ["White"],
    attack: "Area",
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Bahamut Cat",
    evolved: "Crazed Bahamut Cat",
    true: "Awakened Bahamut Cat",
    type: ["White"],
    attack: "Area",
    rarity:["Legend Cats, Special"],
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Cat God the Great",
    evolved: "Cat God the Awesome",
    true: "Cat God the Golden",
    type: ["White"],
    attack: "Area",
    rarity:["Legend Cats, Special"],
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  // Legend Cats from Stories of Legend
  {
    name: "Ururun Wolf",
    evolved: "Ururun Cat",
    true: "Awakened Ururun",
    type: ["White"],
    attack: "Area",
    rarity:["Legend Cats, Special"],
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Li'l Nyandam",
    evolved: "Dark Emperor Catdam",
    true: "Schoolbus Nyandam",
    type: ["White"],
    attack: "Area",
    rarity:["Legend Cats, Special"],
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Red Riding Mina",
    evolved: "Crimson Mina",
    true: "Awakened Mina",
    type: ["White"],
    attack: "Area",
    rarity:["Legend Cats, Special"],
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Miyamoku Musashi",
    evolved: "Legendary Musashi",
    true: "Awakened Musashi",
    type: ["White"],
    attack: "Area",
    rarity:["Legend Cats, Special"],
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Mecha-Bun",
    evolved: "Mecha-Bun Mk II",
    true: "Ultimate Mecha-Bun",
    type: ["White"],
    attack: "Area",
    rarity:["Legend Cats, Special"],
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  // Legend Cats from Uncanny Legends
  {
    name: "Filibuster Cat X",
    evolved: "Filibuster Cat Y",
    true: "Metafilibuster",
    type: ["White"],
    attack: "Area",
    rarity:["Legend Cats, Special"],
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Jagando Jr.",
    evolved: "Lord of Ruin Jagando Jr.",
    true: null,
    type: ["White"],
    attack: "Area",
    rarity:["Legend Cats, Special"],
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Idi:N",
    evolved: "Idi:N2",
    true: null,
    type: ["White"],
    attack: "Area",
    rarity:["Legend Cats, Special"],
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Dogumaru",
    evolved: "Doguemon",
    true: "Reborn Warrior Doguemon",
    type: ["White"],
    attack: "Area",
    rarity:["Legend Cats, Special"],
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Urs & Fenrir",
    evolved: "Urs & Minka",
    true: "Awakened Urs",
    type: ["White"],
    attack: "Area",
    rarity:["Legend Cats, Special"],
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Elder Mask Doron",
    evolved: "Cat Mask Doron",
    true: "Awakened Doron",
    type: ["White"],
    attack: "Area",
    rarity:["Legend Cats, Special"],
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Elder Beast Naala",
    evolved: "Storm Beast Naala",
    true: "Awakened Naala",
    type: ["White"],
    attack: "Area",
    rarity:["Legend Cats, Special"],
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },

  {
    name: "Ancient Egg: N000",
    evolved: "Elder Egg: N000",
    true: "Ape Lord Luza",
    type: ["White"],
    attack: "Area",
    rarity:["Legend Cats, Special"],
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },

  {
    name: "Hermit Cat",
    evolved: "Grandmaster Cat",
    true: "Masked Grandmaster Cat",
    type: ["White"],
    attack: "Area",
    rarity:["Legend Cats, Special"],
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },

  {
    name: "Masked Yulala",
    evolved: "Mystic Yulala",
    true: "Spiritual Yulala",
    type: ["White"],
    attack: "Area",
    rarity:["Legend Cats, Special"],
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },

  {
    name: "Master Uril",
    evolved: "Mystic Uril",
    true: null,
    type: ["White"],
    attack: "Area",
    rarity:["Legend Cats, Special"],
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
];
export{legendCats}