const normalCats = [
  {
    name: "Cat",
    type: null,
    attack: "Single",
    evolved: "Macho Cat",
    true: "Mohawk Cat",
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Tank Cat",
    type: null,
    attack: "Area",
    evolved: "Wall Cat",
    true: "Eraser Cat",
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Axe Cat",
    type: ["Red"],
    attack: "Single",
    evolved: "Brave Cat",
    true: "Dark Cat",
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Gross Cat",
    type: ["Floating"],
    attack: "Single",
    evolved: "Sexy Legs Cat",
    true: "Macho Legs Cat",
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Cow Cat",
    type: ["White"],
    attack: "Single",
    evolved: "Giraffe Cat",
    true: "Lion Cat",
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Bird Cat",
    type: ["Black"],
    attack: "Ares",
    evolved: "The Flying Cat",
    true: "UFO Cat",
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Fish Cat",
    type: ["Red", "Alien"],
    attack: "Single",
    evolved: "Whale Cat",
    true: "Island Cat",
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Lizard Cat",
    type: ["Angel"],
    attack: "Single",
    evolved: "Dragon Cat",
    true: "King Dragon Cat",
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Titan Cat",
    type: ["White"],
    attack: "Area",
    evolved: "Mythical Titan Cat",
    true: "Jamiera Cat",
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
];
export{normalCats}