const rareCats = [
  {
    name: "Pogo Cat",
    type: [null],
    attack: "Single",
    evolved: "Masai Cat",
    true: "Jiangshi Cat",
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Wheel Cat",
    type: ["Alien"],
    attack: "Area",
    evolved: "Solar Cat",
    true: "Chill Cat",
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Salon Cat",
    type: [null],
    attack: "Area",
    evolved: "Paris Cat",
    true: "Cyborg Cat",
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Jurassic Cat",
    type: [null],
    attack: "Single",
    evolved: "Jurassic Cat Sitter",
    true: "Catasaurus",
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Viking Cat",
    type: ["Red"],
    attack: "Single",
    evolved: "Thor Cat",
    true: "Maximum the Fighter",
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Pirate Cat",
    type: ["Red"],
    attack: "Single",
    evolved: "Captain Cat",
    true: "Dread Pirate Catley",
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Thief Cat",
    type: [null],
    attack: "Single",
    evolved: "Phantom Thief Cat",
    true: "Goemon Cat",
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Bishop Cat",
    type: ["Floating"],
    attack: "Area",
    evolved: "Monk Cat",
    true: "Sanzo Cat",
  },
  {
    name: "Wushu Cat",
    type: ["Zombie"],
    attack: "Single",
    evolved: "Sifu Cat",
    true: "Shigong Cat",
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    name: "Kung Fu Cat X" ,
    type: [null],
    attack: "Single",
    evolved: "Drunken Master Cat X",
    true: "Iron Claw X",
    nameUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
];
export {rareCats};
