const allCats = [
  //  Normal Cats
  {
    base: "Cat",
    evolved: "Macho Cat",
    true: "Mohawk Cat",
    type: ["None"],
    attack: "Single",
    rarity: ["Normal Cats"],
    baseUrl: "Cat",
    evolvedUrl: "Macho_cat",
    trueUrl: "Mohawk_cat",
    cost: "75¢",
  },
  {
    base: "Tank Cat",
    evolved: "Wall Cat",
    true: "Eraser Cat",
    type: ["None"],
    attack: "Area",
    rarity: ["Normal Cats"],
    baseUrl: "Tank_cat",
    evolvedUrl: "Wall_cat",
    trueUrl: "Eraser_cat",
    cost: "150¢",
  },
  {
    base: "Axe Cat",
    evolved: "Brave Cat",
    true: "Dark Cat",
    type: ["Red"],
    attack: "Single",
    rarity: ["Normal Cats"],
    baseUrl: "Axe_cat",
    evolvedUrl: "Brave_cat",
    trueUrl: "Dark_cat",
    cost: "300¢",
  },
  {
    base: "Gross Cat",
    evolved: "Sexy Legs Cat",
    true: "Macho Legs Cat",
    type: ["Floating"],
    attack: "Single",
    rarity: ["Normal Cats"],
    baseUrl: "Gross_cat",
    evolvedUrl: "Sexy_legs_cat",
    trueUrl: "Macho_legs_cat",
    cost: "600¢",
  },
  {
    base: "Cow Cat",
    evolved: "Giraffe Cat",
    true: "Lion Cat",
    type: ["None"],
    attack: "Single",
    rarity: ["Normal Cats"],
    baseUrl: "Cow_cat",
    evolvedUrl: "Giraffe_cat",
    trueUrl: "Lion_cat",
    cost: "750¢",
  },
  {
    base: "Bird Cat",
    evolved: "UFO Cat",
    true: "The Flying Cat",
    type: ["Angel"],
    attack: "Area",
    rarity: ["Normal Cats"],
    baseUrl: "Bird_cat",
    evolvedUrl: "UFO_cat",
    trueUrl: "The_flying_cat",
    cost: "975¢",
  },
  {
    base: "Fish Cat",
    evolved: "Whale Cat",
    true: "Island Cat",
    type: ["Red"],
    attack: "Single",
    rarity: ["Normal Cats"],
    baseUrl: "Fish_cat",
    evolvedUrl: "Whale_cat",
    trueUrl: "Island_cat",
    cost: "1200¢",
  },
  {
    base: "Lizard Cat",
    evolved: "Dragon Cat",
    true: "King Dragon Cat",
    type: ["Angel"],
    attack: "Single",
    rarity: ["Normal Cats"],
    baseUrl: "Lizard_cat",
    evolvedUrl: "Dragon_cat",
    trueUrl: "King_dragon_cat",
    cost: "1500¢",
  },
  {
    base: "Titan Cat",
    evolved: "Mythical Titan Cat",
    true: "Jamiera Cat",
    type: [
      "Red",
      "Floating",
      "Black",
      "Angel",
      "Alien",
      "Zombie",
      "Aku",
      "Relic",
      "Traitless",
    ],
    attack: "Area",
    rarity: ["Normal Cats"],
    baseUrl: "Titan_cat",
    evolvedUrl: "Mythical_titan_cat",
    trueUrl: "Jamiera_cat",
    cost: "1950¢",
  },
  //  Legend Cats/Special Cats
  {
    base: "Valkyrie Cat",
    evolved: "True Valkyrie Cat",
    true: "Holy Valkyrie Cat",
    type: [
      "Red",
      "Floating",
      "Black",
      "Angel",
      "Alien",
      "Zombie",
      "Aku",
      "Relic",
      "Traitless",
    ],
    attack: "Area",
    rarity: ["Legend Cats", "Special Cats"],
    baseUrl: "Valkyrie_cat",
    evolvedUrl: "True_valkyrie_cat",
    trueUrl: "Holy_valkyrie_cat",
    cost: "3000¢",
  },
  {
    base: "Bahamut Cat",
    evolved: "Crazed Bahamut Cat",
    true: "Awakened Bahamut Cat",
    type: ["None"],
    attack: "Area",
    rarity: ["Legend Cats", "Special Cats"],
    baseUrl: "Bahamut_cat",
    evolvedUrl: "Crazed_bahamut_cat",
    trueUrl: "Awakened_bahamut_cat",
    cost: "4500¢",
  },
  {
    base: "Ururun Wolf",
    evolved: "Ururun Cat",
    true: "Awakened Ururun",
    type: [
      "Red",
      "Floating",
      "Black",
      "Angel",
      "Alien",
      "Zombie",
      "Aku",
      "Relic",
      "Traitless",
    ],
    attack: "Area",
    rarity: ["Legend Cats", "Special Cats"],
    baseUrl: "Ururun_wolf",
    evolvedUrl: "Ururun_cat",
    trueUrl: "Awakened_ururun",
    cost: "4950¢",
  },
  {
    base: "Red Riding Mina",
    evolved: "Crimson Mina",
    true: "Awakened Mina",
    type: ["Relic"],
    attack: "Area",
    rarity: ["Legend Cats", "Special Cats"],
    baseUrl: "Red_riding_mina",
    evolvedUrl: "Crimson_mina",
    trueUrl: "Awakened_mina",
    cost: "3900¢",
  },
  {
    base: "Miyamoku Musashi",
    evolved: "Heroic Musashi",
    true: "Awakened Musashi",
    type: ["Relic"],
    attack: "Area",
    rarity: ["Legend Cats", "Special Cats"],
    baseUrl: "Miyamoku_musashi",
    evolvedUrl: "Heroic_musashi",
    trueUrl: "Awakened_musashi",
    cost: "4800¢",
  },
  {
    base: "Jagando Jr.",
    evolved: "Lord of Ruin Jagando Jr.",
    true: null,
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Cats", "Special Cats"],
    baseUrl: "Jagando_jr.",
    evolvedUrl: "Lord_of_ruin_jagando_jr.",
    trueUrl: null,
    cost: "4200¢",
  },
  {
    base: "Urs & Fenrir",
    evolved: "Urs & Minka",
    true: "Awakened Urs",
    type: [
      "Red",
      "Floating",
      "Black",
      "Angel",
      "Alien",
      "Zombie",
      "Aku",
      "Relic",
      "Traitless",
    ],
    attack: "Area",
    rarity: ["Legend Cats", "Special Cats"],
    baseUrl: "Urs_&_fenrir",
    evolvedUrl: "Urs_&_minka",
    trueUrl: "Awakened_urs",
    cost: "4875¢",
  },
  {
    base: "Elder Mask Doron",
    evolved: "Cat Mask Doron",
    true: "Awakened Doron",
    type: ["Relic"],
    attack: "Area",
    rarity: ["Legend Cats", "Special Cats"],
    baseUrl: "Elder_mask_doron",
    evolvedUrl: "Cat_mask_doron",
    trueUrl: "Awakened_doron",
    cost: "1800¢",
  },
  {
    base: "Elder Beast Naala",
    evolved: "Storm Beast Naala",
    true: "Awakened Naala",
    type: ["Relic"],
    attack: "Area",
    rarity: ["Legend Cats", "Special Cats"],
    baseUrl: "Elder_Beast_Naala",
    evolvedUrl: "Storm_beast_naala",
    trueUrl: "Awakened_naala",
    cost: "4500¢",
  },
  //  Special Cats
  {
    base: "Ninja Cat",
    evolved: "Ninja Frog Cat",
    true: "Flying Ninja Cat",
    type: ["Red"],
    attack: "Single",
    rarity: ["Special Cats"],
    baseUrl: "Ninja_Cat",
    evolvedUrl: "Ninja_frog_cat",
    trueUrl: "Flying_ninja_cat",
    cost: "300¢",
  },
  {
    base: "Sumo Cat",
    evolved: "Madame Sumo",
    true: "Riceball Cat",
    type: ["None"],
    attack: "Single",
    rarity: ["Special Cats"],
    baseUrl: "Sumo_cat",
    evolvedUrl: "Madame_sumo",
    trueUrl: "Riceball_cat",
    cost: "300¢",
  },
  {
    base: "Samurai Cat",
    evolved: "Knight Cat",
    true: "Pastry Cat",
    type: [
      "Red",
      "Floating",
      "Black",
      "Angel",
      "Alien",
      "Zombie",
      "Aku",
      "Relic",
      "Traitless",
    ],
    attack: "Single",
    rarity: ["Special Cats"],
    baseUrl: "Samurai_cat",
    evolvedUrl: "Knight_cat",
    trueUrl: "Pastry_cat",
    cost: "525¢",
  },
  {
    base: "Zombie Cat",
    evolved: "Devil Cat",
    true: "Skelecat",
    type: ["Red", "Zombie"],
    attack: "Area",
    rarity: ["Special Cats"],
    baseUrl: "Zombie_Cat",
    evolvedUrl: "Devil_cat",
    trueUrl: "Skelecat",
    cost: "1125¢",
  },
  {
    base: "Cats in a Box",
    evolved: "Cat Gang",
    true: "Heavy Assault C.A.T.",
    type: ["Black"],
    attack: "Area",
    rarity: ["Special Cats"],
    baseUrl: "Cats_in_a_box",
    evolvedUrl: "Cat_gang",
    trueUrl: "Heavy_assault_c.a.t.",
    cost: "1125¢",
  },
  {
    base: "Boogie Cat",
    evolved: "Samba Cat",
    true: "Gato Amigo",
    type: [
      "Red",
      "Floating",
      "Black",
      "Angel",
      "Alien",
      "Zombie",
      "Aku",
      "Relic",
      "Traitless",
    ],
    attack: "Single",
    rarity: ["Special Cats"],
    baseUrl: "Boogie_cat",
    evolvedUrl: "Samba_cat",
    trueUrl: "Gato_amigo",
    cost: "75¢",
  },
  {
    base: "Mr.",
    evolved: "Super Mr.",
    true: "Hyper Mr.",
    type: ["None"],
    attack: "Area",
    rarity: ["Special Cats"],
    baseUrl: "Mr.",
    evolvedUrl: "Super_mr.",
    trueUrl: "Hyper_mr.",
    cost: "825¢",
  },
  {
    base: "Kung Fu Cat",
    evolved: "Drunken Master Cat",
    true: "Dancer Cat",
    type: ["None"],
    attack: "Area",
    rarity: ["Special Cats"],
    baseUrl: "Kung_fu_cat",
    evolvedUrl: "Drunken_master_cat",
    trueUrl: "Dancer_cat",
    cost: "2250¢",
  },
  {
    base: "Tricycle Cat",
    evolved: "Biker Cat",
    true: "Unicycle Cat",
    type: ["None"],
    attack: "Area",
    rarity: ["Special Cats"],
    baseUrl: "Tricycle_cat",
    evolvedUrl: "Biker_cat",
    trueUrl: "Unicycle_cat",
    cost: "525¢",
  },
  //  Rare Cats
  {
    base: "Pogo Cat",
    evolved: "Masai Cat",
    true: "Jiangshi Cat",
    type: ["None"],
    attack: "Single",
    rarity: ["Rare Cats"],
    baseUrl: "Pogo_cat",
    evolvedUrl: "Masai_cat",
    trueUrl: "Jiangshi_cat",
    cost: "360¢ | 240¢",
  },
  {
    base: "Wheel Cat",
    evolved: "Solar Cat",
    true: "Chill Cat",
    type: ["Alien"],
    attack: "Area",
    rarity: ["Rare Cats"],
    baseUrl: "Wheel_Cat",
    evolvedUrl: "Solar_cat",
    trueUrl: "Chill_cat",
    cost: "1050¢",
  },
  {
    base: "Salon Cat",
    evolved: "Paris Cat",
    true: "Cyborg Cat",
    type: ["None"],
    attack: "Area",
    rarity: ["Rare Cats"],
    baseUrl: "Salon_cat",
    evolvedUrl: "Paris_cat",
    trueUrl: "Cyborg_cat",
    cost: "900¢",
  },
  {
    base: "Jurassic Cat",
    evolved: "Jurassic Cat Sitter",
    true: "Catasaurus",
    type: ["None"],
    attack: "Single",
    rarity: ["Rare Cats"],
    baseUrl: "Jurassic_cat",
    evolvedUrl: "Jurassic_cat_sitter",
    trueUrl: "Catasaurus",
    cost: "525¢",
  },
  {
    base: "Viking Cat",
    evolved: "Thor Cat",
    true: "Maximum the Fighter",
    type: ["Red"],
    attack: "Single",
    rarity: ["Rare Cats"],
    baseUrl: "Viking_cat",
    evolvedUrl: "Thor_cat",
    trueUrl: "Maximum_the_fighter",
    cost: "525¢",
  },
  {
    base: "Pirate Cat",
    evolved: "Captain Cat",
    true: "Dread Pirate Catley",
    type: ["Red"],
    attack: "Single",
    rarity: ["Rare Cats"],
    baseUrl: "Pirate_cat",
    evolvedUrl: "Captain_cat",
    trueUrl: "Dread_pirate_catley",
    cost: "¢",
  },
  {
    base: "Thief Cat",
    evolved: "Phantom Thief Cat",
    true: "Goemon Cat",
    type: ["None"],
    attack: "Single",
    rarity: ["Rare Cats"],
    baseUrl: "Thief_Cat",
    evolvedUrl: "Phantom_thief_cat",
    trueUrl: "Goemon_cat",
    cost: "495¢",
  },
  {
    base: "Bishop Cat",
    evolved: "Monk Cat",
    true: "Sanzo Cat",
    type: ["Floating"],
    attack: "Single",
    rarity: ["Rare Cats"],
    baseUrl: "Bishop_cat",
    evolvedUrl: "Monk_cat",
    trueUrl: "Sanzo_cat",
    cost: "495¢",
  },
  {
    base: "Wushu Cat",
    evolved: "Sifu Cat",
    true: "Shigong Cat",
    type: ["Zombie"],
    attack: "Single",
    rarity: ["Rare Cats"],
    baseUrl: "Wushu_Cat",
    evolvedUrl: "Sifu_cat",
    trueUrl: "Shigong_cat",
    cost: "360¢",
  },
  {
    base: "Kung Fu Cat X",
    evolved: "Drunken Master Cat X",
    true: "Iron Claw X",
    type: ["None"],
    attack: "Single",
    rarity: ["Rare Cats"],
    baseUrl: "Kung_fu_cat_x",
    evolvedUrl: "Drunken_master_cat_x",
    trueUrl: "Iron_claw_x",
    cost: "2340¢",
  },
  //  Super Rare Cats
  {
    base: "Hip Hop Cat",
    evolved: "Dancer Cat",
    true: "Breakdancer Cat",
    type: ["Red"],
    attack: "Single",
    rarity: ["Super Rare"],
    baseUrl: "Hip_hop_cat",
    evolvedUrl: "Dancing_flasher_cat",
    trueUrl: "Can_can_cat",
    cost: "675¢",
  },
  {
    base: "Apple Cat",
    evolved: "Face Cat",
    true: "iCat",
    type: ["Red"],
    attack: "Single",
    rarity: ["Super Rare"],
    baseUrl: "Apple_cat",
    evolvedUrl: "Face_cat",
    trueUrl: "iCat",
    cost: "825¢",
  },
  {
    base: "Sushi Cat",
    evolved: "Fried Shrimp Cat",
    true: "Roe Cat",
    type: ["Red"],
    attack: "Area",
    rarity: ["Super Rare"],
    baseUrl: "Sushi_cat",
    evolvedUrl: "Fried_shrimp_cat",
    trueUrl: "Roe_cat",
    cost: "1425¢",
  },
  {
    base: "Bodhisattva Cat",
    evolved: "Avalokitesvara Cat",
    true: "Tathagata Cat",
    type: ["Floating"],
    attack: "Area",
    rarity: ["Super Rare"],
    baseUrl: "Bodhisattva_cat",
    evolvedUrl: "Avalokitesvara_cat",
    trueUrl: "Tathagata_cat",
    cost: "1650¢",
  },
  {
    base: "Delinquent Cat",
    evolved: "Angry Delinquent Cat",
    true: "Ultra Delinquent Cat",
    type: ["Floating"],
    attack: "Area",
    rarity: ["Super Rare"],
    baseUrl: "Delinquent_cat",
    evolvedUrl: "Angry_delinquent_cat",
    trueUrl: "Ultra_delinquent_cat",
    cost: "1500¢",
  },
  {
    base: "Bath Cat",
    evolved: "Sexy Bath Cat",
    true: "Luxury Bath Cat",
    type: ["Red"],
    attack: "Single",
    rarity: ["Super Rare"],
    baseUrl: "Bath_Cat",
    evolvedUrl: "Sexy_bathtub_cat",
    trueUrl: "Luxury_bath_cat",
    cost: "750¢",
  },
  {
    base: "Juliet Cat",
    evolved: "Princess Juliet Cat",
    true: "Juliet the Maiko",
    type: ["Angel"],
    attack: "Area",
    rarity: ["Super Rare"],
    baseUrl: "Juliet_cat",
    evolvedUrl: "Princess_juliet_cat",
    trueUrl: "Juliet_the_maiko",
    cost: "825¢",
  },
  {
    base: "Weightlifter Cat",
    evolved: "Ring Girl Cat",
    true: "Pizza Cat",
    type: ["Black"],
    attack: "Area",
    rarity: ["Super Rare"],
    baseUrl: "Weightlifter_cat",
    evolvedUrl: "Ring_girl_cat",
    trueUrl: "Pizza_cat",
    cost: "1365¢",
  },
  {
    base: "Figure Skating Cats",
    evolved: "Drama Cats",
    true: "Slapstick Cats",
    type: ["None"],
    attack: "Area",
    rarity: ["Super Rare"],
    baseUrl: "Figure_skating_cats",
    evolvedUrl: "Drama_cats",
    trueUrl: "Slapstick_cats",
    cost: "¢",
  },
  //  Uber Super Rare Cats
  {
    base: "Baby Cat",
    evolved: "Baby Cats",
    true: "Cats in the Cradle",
    type: ["Metal"],
    attack: "Area",
    rarity: ["Uber Super Rare"],
    baseUrl: "Baby_cat",
    evolvedUrl: "Baby_cats",
    trueUrl: "Cats_in_the_cradle",
    cost: "3150¢",
  },
  {
    base: "Kuu",
    evolved: "Kuu Type γ",
    true: "Divine Kuu",
    type: ["Red", "Black"],
    attack: "Area",
    rarity: ["Uber Super Rare"],
    baseUrl: "Kuu",
    evolvedUrl: "Kuu_type_γ",
    trueUrl: "Divine_kuu",
    cost: "4200¢",
  },
  {
    base: "Sakura Sonic",
    evolved: "Afterschool Sakura",
    true: "Sacred Blade Sakura",
    type: ["Metal"],
    attack: "Area",
    rarity: ["Uber Super Rare"],
    baseUrl: "Sakura_sonic",
    evolvedUrl: "Afterschool_sakura",
    trueUrl: "Sacred_blade_sakura",
    cost: "4200¢",
  },
  {
    base: "Kai",
    evolved: "Kai Type μ",
    true: "Divine Kai",
    type: ["Black"],
    attack: "Area",
    rarity: ["Uber Super Rare"],
    baseUrl: "Kai",
    evolvedUrl: "Kai_type_μ",
    trueUrl: "Divine_kai",
    cost: "3990¢",
  },
  {
    base: "Coppermine",
    evolved: "Coppermine Type κ",
    true: "Divine Coppermine",
    type: ["Floating"],
    attack: "Area",
    rarity: ["Uber Super Rare"],
    baseUrl: "Coppermine",
    evolvedUrl: "Coppermine_type_κ",
    trueUrl: "Divine_coppermine",
    cost: "3720¢",
  },
  {
    base: "Kalisa",
    evolved: "Kalisa Type χ",
    true: "Divine Kalisa",
    type: ["Angel"],
    attack: "Single",
    rarity: ["Uber Super Rare"],
    baseUrl: "Kalisa",
    evolvedUrl: "Kalisa_type_χ",
    trueUrl: "Divine_kalisa",
    cost: "4125¢",
  },
  {
    base: "Sanada Yukimura",
    evolved: "Wargod Yukimura",
    true: "Immortal Yukimura",
    type: ["Black"],
    attack: "Area",
    rarity: ["Uber Super Rare"],
    baseUrl: "Sanada_yukimura",
    evolvedUrl: "Wargod_yukimura",
    trueUrl: "Immortal_yukimura",
    cost: "3075¢",
  },
  {
    base: "Warlock and Pierre",
    evolved: "Dark Merchant Babil",
    true: "Mad Doctor Klay",
    type: ["Floating", "Alien"],
    attack: "Area",
    rarity: ["Uber Super Rare"],
    baseUrl: "Warlock_and_pierre",
    evolvedUrl: "Dark_merchant_babil",
    trueUrl: "Mad_doctor_klay",
    cost: "6135¢",
  },
  {
    base: "Akira",
    evolved: "Shadow Akira",
    true: "Inferno Akira",
    type: ["Alien"],
    attack: "Area",
    rarity: ["Uber Super Rare"],
    baseUrl: "Akira",
    evolvedUrl: "Shadow_akira",
    trueUrl: "Inferno_akira",
    cost: "4860¢",
  },
  //  Legend Rare Cats
  {
    base: "Akuma",
    evolved: "Akuma CC",
    true: null,
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "Akuma",
    evolvedUrl: "Akuma_cc",
    trueUrl: null,
    cost: "4500¢",
  },
  {
    base: "Black Zeus",
    evolved: "Dark Lord Zeus",
    true: null,
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "Black_Zeus",
    evolvedUrl: "Dark_lord_zeus",
    trueUrl: null,
    cost: "4950¢",
  },
  {
    base: "Doktor Heaven",
    evolved: "Professor Abyss",
    true: null,
    type: ["Black", "Alien"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "Doktor_heaven",
    evolvedUrl: "Professor_abyss",
    trueUrl: null,
    cost: "5400¢",
  },
  {
    base: "Emperor Cat",
    evolved: "Tyrant Cat",
    true: null,
    type: [
      "Red",
      "Floating",
      "Black",
      "Metal",
      "Angel",
      "Alien",
      "Zombie",
      "Aku",
      "Relic",
    ],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "Emperor_Cat",
    evolvedUrl: "Tyrant_cat",
    trueUrl: null,
    cost: "4500¢",
  },
  {
    base: "Gaia the Creator",
    evolved: "Gaia the Supreme",
    true: null,
    type: [
      "Red",
      "Floating",
      "Black",
      "Metal",
      "Angel",
      "Alien",
      "Zombie",
      "Aku",
      "Relic",
    ],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "Gaia_the_Creator",
    evolvedUrl: "Gaia_the_Supreme",
    trueUrl: null,
    cost: "4470¢",
  },
  {
    base: "Headmistress Jeanne",
    evolved: "Headmistress Jeanne ψ",
    true: null,
    type: ["Red", "Floating"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "Headmistress_jeanne",
    evolvedUrl: "Headmistress_jeanne_ψ",
    trueUrl: null,
    cost: "4830¢",
  },
  {
    base: "High Lord Babel",
    evolved: "Babel the Darkflame",
    true: "God-Emperor Babel",
    type: ["Red", "Floating"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "High_lord_babel",
    evolvedUrl: "Babel_the_darkflame",
    trueUrl: "God-Emperor_babel",
    cost: "6750¢",
  },
  {
    base: "Kyosaka Nanaho",
    evolved: "True Kyosaka Nanaho",
    true: null,
    type: ["Metal"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "Kyosaka_nanaho",
    evolvedUrl: "True_kyosaka_nanaho",
    trueUrl: null,
    cost: "4050¢",
  },
  {
    base: "Legeluga",
    evolved: "Legelan Pasalan",
    true: null,
    type: ["None"],
    attack: "Single",
    rarity: ["Legend Rare"],
    baseUrl: "Legeluga",
    evolvedUrl: "Legelan_pasalan",
    trueUrl: null,
    cost: "4500¢",
  },
  {
    base: "Lumina",
    evolved: "Luminalia",
    true: null,
    type: ["Alien"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "Lumina",
    evolvedUrl: "Luminalia",
    trueUrl: null,
    cost: "1100¢ | 3675¢",
  },
  {
    base: "Mighty Kristul Muu",
    evolved: "Doom Engine Pandora",
    true: null,
    type: ["Zombie"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "Mighty_kristul_muu",
    evolvedUrl: "Doom_engine_pandora",
    trueUrl: null,
    cost: "4650¢",
  },
  {
    base: "Musashi Miyamoto",
    evolved: "Wargod Miyamoto",
    true: null,
    type: ["Black"],
    attack: "Single",
    rarity: ["Legend Rare"],
    baseUrl: "Musashi_miyamoto",
    evolvedUrl: "Wargod_miyamoto",
    trueUrl: null,
    cost: "4275¢",
  },
  {
    base: "Ushiwakamaru",
    evolved: "Colossal Benkei",
    true: null,
    type: ["Angel"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "Ushiwakamaru",
    evolvedUrl: "Colossal_benkei",
    trueUrl: null,
    cost: "825¢ | 6000¢",
  },
  {
    base: "Wonder MOMOCO",
    evolved: "Cutie MOMOCO",
    true: null,
    type: ["Red", "Black", "Angel"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "Wonder_momoco",
    evolvedUrl: "Cutie_momoco",
    trueUrl: null,
    cost: "4500¢",
  },
];

export { allCats };
