
const allCats = [
  //  Normal Cats
  {
    base: "Cat",
    evolved: "Macho Cat",
    true: "Mohawk Cat",
    type: null,
    attack: "Single",
    rarity: ["Normal Cats"],
    baseUrl: "Cat",
    evolvedUrl: "Macho_cat",
    trueUrl: "Mohawk_cat",
  },
  {
    base: "Tank Cat",
    evolved: "Wall Cat",
    true: "Eraser Cat",
    type: null,
    attack: "Area",
    rarity: ["Normal Cats"],
    baseUrl: "Tank_cat",
    evolvedUrl: "Wall_cat",
    trueUrl: "Eraser_cat",
  },
  {
    base: "Axe Cat",
    evolved: "Brave Cat",
    true: "Dark Cat",
    type: ["Red"],
    attack: "Single",
    rarity: ["Normal Cats"],
    baseUrl: "Axe_cat",
    evolvedUrl: "Brave_cat",
    trueUrl: "Dark_cat",
  },
  {
    base: "Gross Cat",
    evolved: "Sexy Legs Cat",
    true: "Macho Legs Cat",
    type: ["Floating"],
    attack: "Single",
    rarity: ["Normal Cats"],
    baseUrl: "Gross_cat",
    evolvedUrl: "Sexy_legs_cat",
    trueUrl: "Macho_legs_cat",
  },
  {
    base: "Cow Cat",
    evolved: "Giraffe Cat",
    true: "Lion Cat",
    type: null,
    attack: "Single",
    rarity: ["Normal Cats"],
    baseUrl: "Cow_cat",
    evolvedUrl: "Giraffe_cat",
    trueUrl: "Lion_cat",
  },
  {
    base: "Bird Cat",
    evolved: "UFO Cat",
    true: "The Flying Cat",
    type: ["Angel"],
    attack: "Area",
    rarity: ["Normal Cats"],
    baseUrl: "Bird_cat",
    evolvedUrl: "UFO_cat",
    trueUrl: "The_flying_cat",
  },
  {
    base: "Fish Cat",
    evolved: "Whale Cat",
    true: "Island Cat",
    type: ["Red"],
    attack: "Single",
    rarity: ["Normal Cats"],
    baseUrl: "Fish_cat",
    evolvedUrl: "Whale_cat",
    trueUrl: "Island_cat",
  },
  {
    base: "Lizard Cat",
    evolved: "Dragon Cat",
    true: "King Dragon Cat",
    type: ["Angel"],
    attack: "Single",
    rarity: ["Normal Cats"],
    baseUrl: "Lizard_cat",
    evolvedUrl: "Dragon_cat",
    trueUrl: "King_dragon_cat",
  },
  {
    base: "Titan Cat",
    evolved: "Mythical Titan Cat",
    true: "Jamiera Cat",
    type: [
      "Red",
      "Floating",
      "Black",
      "Angel",
      "Alien",
      "Zombie",
      "Aku",
      "Relic",
      "Traitless",
    ],
    attack: "Area",
    rarity: ["Normal Cats"],
    baseUrl: "Titan_cat",
    evolvedUrl: "Mythical_titan_cat",
    trueUrl: "Jamiera_cat",
  },
  //  Legend Cats/Special Cats
  {
    base: "Valkyrie Cat",
    evolved: "True Valkyrie Cat",
    true: "Holy Valkyrie Cat",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Cats, Special Cats"],
    baseUrl:
      "Valkyrie_cat",
    evolvedUrl:
      "True_valkyrie_cat",
    trueUrl:
      "",
  },
  {
    base: "Bahamut Cat",
    evolved: "Crazed Bahamut Cat",
    true: "Awakened Bahamut Cat",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Cats, Special Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Ururun Wolf",
    evolved: "Ururun Cat",
    true: "Awakened Ururun",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Cats, Special Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Red Riding Mina",
    evolved: "Crimson Mina",
    true: "Awakened Mina",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Cats, Special Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Miyamoku Musashi",
    evolved: "Legendary Musashi",
    true: "Awakened Musashi",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Cats, Special Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Jagando Jr.",
    evolved: "Lord of Ruin Jagando Jr.",
    true: null,
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Cats, Special Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Urs & Fenrir",
    evolved: "Urs & Minka",
    true: "Awakened Urs",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Cats, Special Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Elder Mask Doron",
    evolved: "Cat Mask Doron",
    true: "Awakened Doron",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Cats, Special Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Elder Beast Naala",
    evolved: "Storm Beast Naala",
    true: "Awakened Naala",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Cats, Special Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  //  Special Cats
  {
    base: "Ninja Cat",
    evolved: "Ninja Frog Cat",
    true: "Flying Ninja Cat",
    type: ["Red"],
    attack: "Single",
    rarity: ["Special Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Sumo Cat",
    evolved: "Madame Sumo",
    true: "Riceball Cat",
    type: ["White"],
    attack: "Single",
    rarity: ["Special Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Samurai Cat",
    evolved: "Sword Master Cat",
    true: "Elemental Duelist Cat",
    type: ["Black"],
    attack: "Single",
    rarity: ["Special Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Zombie Cat",
    evolved: "Necromancer Cat",
    true: "Zombie King Cat",
    type: ["Zombie"],
    attack: "Single",
    rarity: ["Special Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Cats in a Box",
    evolved: "Box Cats",
    true: "Heavy Assault C.A.T.",
    type: ["White"],
    attack: "Single",
    rarity: ["Special Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Boogie Cat",
    evolved: "Samba Cat",
    true: "Gato Amigo",
    type: ["White"],
    attack: "Single",
    rarity: ["Special Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Skirt Cat",
    evolved: "Panties Cat",
    true: "The White Rabbit",
    type: ["White"],
    attack: "Single",
    rarity: ["Special Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Mr.",
    evolved: "Hyper Mr.",
    true: "Ultimate Bondage Cat",
    type: ["White"],
    attack: "Single",
    rarity: ["Special Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Bondage Cat",
    evolved: "Dom Cat",
    true: "Masochist Cat",
    type: ["White"],
    attack: "Single",
    rarity: ["Special Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Tricycle Cat",
    evolved: "Bicycle Cat",
    true: "Unicycle Cat",
    type: ["Metal"],
    attack: "Single",
    rarity: ["Special Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  //  Rare Cats
  {
    base: "Pogo Cat",
    evolved: "Masai Cat",
    true: "Jiangshi Cat",
    type: null,
    attack: "Single",
    rarity: ["Rare Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Wheel Cat",
    evolved: "Solar Cat",
    true: "Chill Cat",
    type: ["Alien"],
    attack: "Area",
    rarity: ["Rare Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Salon Cat",
    evolved: "Paris Cat",
    true: "Cyborg Cat",
    type: null,
    attack: "Area",
    rarity: ["Rare Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Jurassic Cat",
    evolved: "Jurassic Cat Sitter",
    true: "Catasaurus",
    type: null,
    attack: "Single",
    rarity: ["Rare Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Viking Cat",
    evolved: "Thor Cat",
    true: "Maximum the Fighter",
    type: ["Red"],
    attack: "Single",
    rarity: ["Rare Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Pirate Cat",
    evolved: "Captain Cat",
    true: "Dread Pirate Catley",
    type: ["Red"],
    attack: "Single",
    rarity: ["Rare Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Thief Cat",
    evolved: "Phantom Thief Cat",
    true: "Goemon Cat",
    type: null,
    attack: "Single",
    rarity: ["Rare Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Bishop Cat",
    evolved: "Monk Cat",
    true: "Sanzo Cat",
    type: ["Floating"],
    attack: "Area",
    rarity: ["Rare Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Wushu Cat",
    evolved: "Sifu Cat",
    true: "Shigong Cat",
    type: ["Zombie"],
    attack: "Single",
    rarity: ["Rare Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Kung Fu Cat X",
    evolved: "Drunken Master Cat X",
    true: "Iron Claw X",
    type: null,
    attack: "Single",
    rarity: ["Rare Cats"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  //  Super Rare Cats
  {
    base: "Hip Hop Cat",
    evolved: "Dancer Cat",
    true: "Breakdancer Cat",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Super Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Apple Cat",
    evolved: "Apple Cat Mk II",
    true: "Apple Cat Mk III",
    type: ["Red"],
    attack: "Area",
    rarity: ["Super Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Sushi Cat",
    evolved: "Sashimi Cat",
    true: "Roe Cat",
    type: ["Alien"],
    attack: "Area",
    rarity: ["Super Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Bodhisattva Cat",
    evolved: "Avalokitesvara Cat",
    true: "Megaphrodite",
    type: ["Angel"],
    attack: "Area",
    rarity: ["Super Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Delinquent Cat",
    evolved: "Angry Delinquent Cat",
    true: "Dark Lazer",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Super Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Bath Cat",
    evolved: "Sexy Bath Cat",
    true: "Hyakutaro",
    type: ["Red", "Black"],
    attack: "Area",
    rarity: ["Super Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Juliet Cat",
    evolved: "Mademoiselle Cat",
    true: "Cataur",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Super Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Weightlifter Cat",
    evolved: "Ring Girl Cat",
    true: "Iron Claw",
    type: ["Metal"],
    attack: "Single",
    rarity: ["Super Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Figure Skating Cats",
    evolved: "Pairs Figure Skating Cats",
    true: "Dreamy Figure Skating Cats",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Super Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  //  Uber Super Rare Cats
  {
    base: "Baby Cat",
    evolved: "Adult Cat",
    true: "Evil Cat",
    type: ["Metal"],
    attack: "Area",
    rarity: ["Uber Super Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Kuu",
    evolved: "Kuu Type γ",
    true: "Kuu Type Ω",
    type: ["Alien"],
    attack: "Area",
    rarity: ["Uber Super Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Frosty Kai",
    evolved: "Frosty Kai Type μ",
    true: "241-3",
    type: ["Alien", "Angel"],
    attack: "Area",
    rarity: ["Uber Super Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Kai",
    evolved: "Kai Type μ",
    true: "Divine Kai",
    type: ["Black"],
    attack: "Area",
    rarity: ["Uber Super Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Coppermine",
    evolved: "Coppermine Type κ",
    true: "Divine Coppermine",
    type: ["Floating"],
    attack: "Area",
    rarity: ["Uber Super Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Kalisa",
    evolved: "Kalisa Type χ",
    true: "Divine Kalisa",
    type: ["Angel"],
    attack: "Single",
    rarity: ["Uber Super Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Sanada Yukimura",
    evolved: "Wargod Yukimura",
    true: "Immortal Yukimura",
    type: ["Black"],
    attack: "Area",
    rarity: ["Uber Super Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Warlock and Pierre",
    evolved: "Dark Merchant Babil",
    true: "Mad Doctor Klay",
    type: ["Floating", "Alien"],
    attack: "Area",
    rarity: ["Uber Super Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Akira",
    evolved: "Shadow Akira",
    true: "Inferno Akira",
    type: ["Alien"],
    attack: "Area",
    rarity: ["Uber Super Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  //  Legend Rare Cats
  {
    base: "Akuma",
    evolved: "Shin Akuma",
    true: "Oni Akuma",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Black Zeus",
    evolved: "Black Zeus Mk II",
    true: "Black Zeus Mk III",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Doctor Heaven",
    evolved: "Doctor Heaven CC",
    true: "Doctor Heaven CC Mk II",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Emperor Cat",
    evolved: "Emperor Cat CC",
    true: "Emperor Cat CC Mk II",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Gaia the Creator",
    evolved: "Gaia the Supreme",
    true: "Gaia the Merciful",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Headmistress Jeanne",
    evolved: "Headmistress Jeanne CC",
    true: "Headmistress Jeanne CC Mk II",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "High Lord Babel",
    evolved: "High Lord Babel CC",
    true: "High Lord Babel CC Mk II",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Kyosaka Nanaho",
    evolved: "Kyosaka Nanaho & Cat",
    true: "Kyosaka Nanaho & Cat CC",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Legeluga",
    evolved: "Legelan Pasalan",
    true: "Awakened Legeluga",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Lumina",
    evolved: "Luminalia",
    true: "Lumina-Nyanko",
    type: ["Alien", "Metal"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Mighty Kristul Muu",
    evolved: "Mighty Glass Cat",
    true: "Mighty Kristul Nurse",
    type: ["Angel", "Metal"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Mushashi Miyamoto",
    evolved: "Legendary Mushashi",
    true: "Awakened Mushashi",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Ushiwakamaru",
    evolved: "Ushiwakamaru CC",
    true: "Ushiwakamaru CC Mk II",
    type: ["Traitless"],
    attack: "Area",
    rarity: ["Legend Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
  {
    base: "Wonder MOMOCO",
    evolved: "Cutie MOMOCO",
    true: null,
    type: ["Red", "Black", "Angel"],
    attack: "area",
    rarity: ["Legend Rare"],
    baseUrl: "",
    evolvedUrl: "",
    trueUrl: "",
  },
];

export {allCats};
